### ISSUE TITLE
State Pattern

### ISSUE THREAD

**Issue by gururise** [HauntedHeavy/BananaWars#1]
# Summary
Every time you want to add a new feature (ie. jump, run, slide, etc) to a player character, you need to add more if-then logic to the player controller.  As you add more features to the player, the programming logic becomes very complex, inter-dependent and brittle.  There must be a better way...

# Solution
The "[state pattern](https://gameprogrammingpatterns.com/state.html)" uses a Finite State Machine (FSM) to build a series of states that can be transitioned to cleanly from your character controller.
![image](https://user-images.githubusercontent.com/4380009/179815657-355247e9-8369-4113-8ad4-39d947750982.png)

# Example Videos
1. Introduction to State Machines: https://www.youtube.com/watch?v=-ZP2Xm-mY4E
2. Implementing the State Pattern in Godot: https://www.youtube.com/watch?v=Bm3sRxDb3js
3. Advanced State Machines: https://www.youtube.com/watch?v=DPxIMVC0oZA

# Task
Build a state machine to replace the if-then logic in the current banana player.  The states will be:
1. idle
2. walk
3. run
4. jump

You should be able to "shoot" from each of those states.

**Comment by Wheeledparasite** [comment]
fixed in 4cd5092d11c585db8d06e6c08fd6e71c7322f6d4
